default_install_hook_types: [pre-commit, pre-push]

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
  # compilers
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.7
    hooks:
      - id: uv-lock
      - id: pip-compile
        name: pip-compile requirements.txt
        args:
          - --generate-hashes
          - pyproject.toml
          - -o requirements.txt
          - --universal
          - --python-version=3.12
        files: ^(pyproject\.toml|uv\.lock)$
      - id: pip-compile
        name: pip-compile requirements-dev.txt
        args:
          - --generate-hashes
          - pyproject.toml
          - -o requirements-dev.txt
          - --universal
          - --python-version=3.12
          - --group=dev
        files: ^(pyproject\.toml|uv\.lock)$
  # linters
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.6.1
    hooks:
      - id: biome-check
        additional_dependencies:
          - '@biomejs/biome@2.3.2'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: local
    hooks:
      - id: ty
        name: run ty check
        entry: uv run --frozen ty check
        language: system
        types: [python]
        pass_filenames: true
      - id: pytest
        name: run pytest with coverage
        entry: uv run --frozen pytest ./tests -q --cov=fundamental --cov-report= --cov-fail-under=90 -n auto
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
      - id: vitest
        name: run vitest
        entry: bash -lc 'cd web && npx --yes vitest run --silent --bail 1 --reporter=dot >/dev/null 2>&1'
        language: system
        types: [javascript]
        pass_filenames: false
        always_run: true
        stages: [pre-push]
